### ISSUE TITLE
How to change authetification methods in datalad-crawler

### ISSUE THREAD

**Issue by mathdugre** [datalad/datalad-crawler#60]
Hi, I was following along [this example](https://datalad-crawler.readthedocs.io/en/latest/demos/track_data_from_webpage.html) from the documentation while adapting it to my needs. Everything worked well, however, when I used `datalad crawl` I entered the wrong authentication methods in the list. Every time I execute `datalad crawl` it retrieves the cached credentials:
```
You need to authenticate with 'some_credential' credentials.
user:
password:
```

The problem is that I would need to pass a token with the user. I tried to find where the cached authentication is, but I was unsuccessfully.

**Comment by yarikoptic** [comment]
The example you point to didn't need any credentials, from that and the name of the credential I assume you setup a new provider... Those should be stored in a user configuration directory I believe, location of which would depend on your system. In Linux it is ~/.config/datalad, and probably providers subdirectory there. Did you find it?

**Comment by yarikoptic** [comment]
May be if you run with `-l debug` datalad would tell you a bit more, eg were it is loading it from?

**Comment by mathdugre** [comment]
Great, I found it. Thank you!

For future reference, on OSX the credentials are stored in `/Users/some_user/Library/Application Support/datalad/`. There is the cookie as well as the providers information.
